name: Laravel

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_libretext
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup test database
        run: php artisan migrate
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_PASSWORD: ""
          DB_DATABASE: test_libretext
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit --filter Feature --stop-on-failure
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_PASSWORD: ""
          DB_DATABASE: test_libretext
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          APP_LOG_LEVEL: ${{ secrets.APP_LOG_LEVEL }}
          LOG_CHANNEL: ${{ secrets.stack }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          WEBWORK_SEED: ${{ secrets.WEBWORK_SEED }}
          IMATHAS_SEED: ${{ secrets.IMATHAS_SEED }}
          BROADCAST_DRIVER: ${{ secrets.BROADCAST_DRIVER }}
          CACHE_DRIVER: ${{ secrets.CACHE_DRIVER }}
          QUEUE_CONNECTION: ${{ secrets.QUEUE_CONNECTION }}
          SESSION_DRIVER:  ${{ secrets.SESSION_DRIVER }}
          SESSION_LIFETIME: ${{ secrets.SESSION_LIFETIME }}
          MAIL_MAILER: ${{ secrets.MAIL_MAILER }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_SECRET: ${{ secrets.MAILGUN_SECRET }}
          MAILGUN_ENDPOINT: ${{ secrets.MAILGUN_ENDPOINT }}
          MAILGUN_ENCRYPTION: ${{ secrets.MAILGUN_ENCRYPTION }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          JWT_TTL: ${{ secrets.JWT_TTL }}
          DEBUGBAR_ENABLED: ${{ secrets.DEBUGBAR_ENABLED }}
          LIBRETEXTS_CLIENT_ID:  ${{ secrets.LIBRETEXTS_CLIENT_ID }}
          LIBRETEXTS_CLIENT_SECRET: ${{ secrets.LIBRETEXTS_CLIENT_SECRET}}
          IS_ME_COOKIE: ${{ secrets.IS_ME_COOKIE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
